baseURL = "http://skoelzer.github.io/"
languageCode = "en-us"
title = "Steven Kölzer"
theme = "kube2"
draft = false
publishDir = "docs"

[Params]
    author = "skoelzer"
    github = "skoelzer"
    twitter = "@SKlzer"